(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"DM_neutrino_model",
  Authors -> {"Gopolang Mohlabeng, Karen Macias Cardenas"},
  Institutions -> {"Queen's University"},
  Emails -> {"gopolang.mohlabeng@queensu.ca, karen.maciascardenas@queensu.ca"},
  URLs -> "http://feynrules.irmp.ucl.ac.be/wiki/DMsimp/",
  References -> {""},
  Version -> "1.0",
  Date -> "2021.09.01"};

FR$ClassesTranslation={A -> V[1], Z -> V[2], W -> V[3], G -> V[4], ghA -> U[1], ghZ -> U[2], ghWp -> U[3], ghWm -> U[4], ghG -> U[5], ve -> F[1], vm -> F[2], vt -> F[3], e -> F[4], mu -> F[5], ta -> F[6], u -> F[7], c -> F[8], t -> F[9], d -> F[10], s -> F[11], b -> F[12], H -> S[1], G0 -> S[2], GP -> S[3], phi1 -> S[4], phi2 -> S[5], eta -> S[6], Phis -> S[7], NR -> F[13], chi -> F[14]};

FR$InteractionOrderPerturbativeExpansion={{NP, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "A" },

V[2] == {
    SelfConjugate -> True,
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "Z" },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "W" },

V[4] == {
    SelfConjugate -> True,
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G" },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "ghA" },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "ghZ" },

U[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWp" },

U[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "ghWm" },

U[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "ghG" },

F[1] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mnu,
    Indices -> {},
    PropagatorLabel -> "ve" },

F[2] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vm" },

F[3] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {},
    PropagatorLabel -> "vt" },

F[4] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Me,
    Indices -> {},
    PropagatorLabel -> "e" },

F[5] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MMU,
    Indices -> {},
    PropagatorLabel -> "mu" },

F[6] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MTA,
    Indices -> {},
    PropagatorLabel -> "ta" },

F[7] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MU,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "u" },

F[8] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MC,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "c" },

F[9] == {
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "t" },

F[10] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MD,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "d" },

F[11] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MS,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "s" },

F[12] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-1/3*Q},
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MB,
    Indices -> {Index[Colour]},
    PropagatorLabel -> "b" },

S[1] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {},
    PropagatorLabel -> "H" },

S[2] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {},
    PropagatorLabel -> "G0" },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {},
    PropagatorLabel -> "GP" },

S[4] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mphi1,
    Indices -> {},
    PropagatorLabel -> "phi1" },

S[5] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mphi2,
    Indices -> {},
    PropagatorLabel -> "phi2" },

S[6] == {
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> Meta,
    Indices -> {},
    PropagatorLabel -> "eta" },

S[7] == {
    SelfConjugate -> False,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> mphis,
    Indices -> {},
    PropagatorLabel -> "Phis" },

F[13] == {
    SelfConjugate -> True,
    PropagatorType -> Straight,
    PropagatorArrow -> False,
    Mass -> MNR,
    Indices -> {},
    PropagatorLabel -> "NR" },

F[14] == {
    SelfConjugate -> True,
    PropagatorArrow -> True,
    PropagatorType -> Straight,
    Mass -> Mchi,
    Indices -> {},
    PropagatorLabel -> "chi" }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[3] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[W];
GaugeXi[ U[5] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];
GaugeXi[ S[4] ] = GaugeXi[S[5]];
GaugeXi[ S[5] ] = GaugeXi[S[6]];
GaugeXi[ S[6] ] = GaugeXi[S[19]];
GaugeXi[ S[7] ] = GaugeXi[S[20]];
GaugeXi[ F[13] ] = GaugeXi[F[99]];
GaugeXi[ F[14] ] = GaugeXi[F[100]];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
mnu[ ___ ] := mnu;
Me[ ___ ] := Me;
MMU[ ___ ] := MMU;
MTA[ ___ ] := MTA;
MU[ ___ ] := MU;
MC[ ___ ] := MC;
MT[ ___ ] := MT;
MD[ ___ ] := MD;
MS[ ___ ] := MS;
MB[ ___ ] := MB;
MH[ ___ ] := MH;
mphi1[ ___ ] := mphi1;
mphi2[ ___ ] := mphi2;
Meta[ ___ ] := Meta;
mphis[ ___ ] := mphis;
MNR[ ___ ] := MNR;
Mchi[ ___ ] := Mchi;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];
TheLabel[ F[7, {__}] ] := TheLabel[F[7]];
TheLabel[ F[8, {__}] ] := TheLabel[F[8]];
TheLabel[ F[9, {__}] ] := TheLabel[F[9]];
TheLabel[ F[10, {__}] ] := TheLabel[F[10]];
TheLabel[ F[11, {__}] ] := TheLabel[F[11]];
TheLabel[ F[12, {__}] ] := TheLabel[F[12]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[6] , S[6] , S[4] , S[4] ] == {{(-I)*(lamphi + lamphic), 0}},

C[ S[6] , S[6] , S[5] , S[5] ] == {{(-I)*(lamphi - lamphic), 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*vev, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*vev, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{I*EL, 0}, {(-I)*EL, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{((-I)*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{(EL^2*(cw - sw)*(cw + sw)*vev)/(4*cw*sw^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{(I*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ -U[3] , U[1] , V[3] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(EL^2*vev)/(4*sw^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*EL^2*vev)/sw^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*EL, 0}, {I*EL, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{(I*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{-1/4*(EL^2*(cw - sw)*(cw + sw)*vev)/(cw*sw^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{((-I)*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{(EL^2*(cw^2 + sw^2)*vev)/(4*cw*sw^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{(I*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{-1/4*(EL^2*(cw^2 + sw^2)*vev)/(cw*sw^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{((-I)*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{GS*SUNF[e3x2, e1x1, e2x1], 0}, {GS*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {GS*SUNF[e1x2, e2x2, e3x2], 0}, {-(GS*SUNF[e1x2, e2x2, e3x2]), 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{I*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {(-I)*GS^2*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ F[13] , F[1] , S[4] ] == {{((-I)*Ynu)/Sqrt[2], 0}, {((-I)*Ynu)/Sqrt[2], 0}},

C[ F[13] , F[1] , S[5] ] == {{-(Ynu/Sqrt[2]), 0}, {Ynu/Sqrt[2], 0}},

C[ F[13] , F[2] , S[4] ] == {{((-I)*Ynu)/Sqrt[2], 0}, {((-I)*Ynu)/Sqrt[2], 0}},

C[ F[13] , F[2] , S[5] ] == {{-(Ynu/Sqrt[2]), 0}, {Ynu/Sqrt[2], 0}},

C[ F[13] , F[3] , S[4] ] == {{((-I)*Ynu)/Sqrt[2], 0}, {((-I)*Ynu)/Sqrt[2], 0}},

C[ F[13] , F[3] , S[5] ] == {{-(Ynu/Sqrt[2]), 0}, {Ynu/Sqrt[2], 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -S[3] ] == {{yb*IndexDelta[e1x2, e2x2], 0}, {-(yt*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -S[3] ] == {{ydo*IndexDelta[e1x2, e2x2], 0}, {-(yup*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -S[3] ] == {{ys*IndexDelta[e1x2, e2x2], 0}, {-(yc*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[2] ] == {{-((yb*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}, {(yb*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[2] ] == {{-((ydo*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}, {(ydo*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[2] ] == {{-((ys*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}, {(ys*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , S[1] ] == {{((-I)*yb*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*yb*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , S[1] ] == {{((-I)*ydo*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*ydo*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , S[1] ] == {{((-I)*ys*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*ys*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[4] , F[1] , -S[3] ] == {{ye, 0}, {0, 0}},

C[ -F[5] , F[2] , -S[3] ] == {{ym, 0}, {0, 0}},

C[ -F[6] , F[3] , -S[3] ] == {{ytau, 0}, {0, 0}},

C[ -F[4] , F[4] , S[2] ] == {{-(ye/Sqrt[2]), 0}, {ye/Sqrt[2], 0}},

C[ -F[5] , F[5] , S[2] ] == {{-(ym/Sqrt[2]), 0}, {ym/Sqrt[2], 0}},

C[ -F[6] , F[6] , S[2] ] == {{-(ytau/Sqrt[2]), 0}, {ytau/Sqrt[2], 0}},

C[ -F[4] , F[4] , S[1] ] == {{((-I)*ye)/Sqrt[2], 0}, {((-I)*ye)/Sqrt[2], 0}},

C[ -F[5] , F[5] , S[1] ] == {{((-I)*ym)/Sqrt[2], 0}, {((-I)*ym)/Sqrt[2], 0}},

C[ -F[6] , F[6] , S[1] ] == {{((-I)*ytau)/Sqrt[2], 0}, {((-I)*ytau)/Sqrt[2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , S[3] ] == {{yc*IndexDelta[e1x2, e2x2], 0}, {-(ys*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , S[3] ] == {{yt*IndexDelta[e1x2, e2x2], 0}, {-(yb*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , S[3] ] == {{yup*IndexDelta[e1x2, e2x2], 0}, {-(ydo*IndexDelta[e1x2, e2x2]), 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[2] ] == {{(yc*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {-((yc*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[2] ] == {{(yt*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {-((yt*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[2] ] == {{(yup*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {-((yup*IndexDelta[e1x2, e2x2])/Sqrt[2]), 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , S[1] ] == {{((-I)*yc*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*yc*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , S[1] ] == {{((-I)*yt*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*yt*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , S[1] ] == {{((-I)*yup*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}, {((-I)*yup*IndexDelta[e1x2, e2x2])/Sqrt[2], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-1/2*EL^2/sw, 0}},

C[ -S[3] , V[1] , V[3] ] == {{-1/2*(EL^2*vev)/sw, 0}},

C[ S[2] , -S[3] , V[3] ] == {{((-1/2*I)*EL)/sw, 0}, {((I/2)*EL)/sw, 0}},

C[ -S[3] , S[1] , V[3] ] == {{EL/(2*sw), 0}, {-1/2*EL/sw, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*EL, 0}, {I*EL, 0}, {I*EL, 0}, {(-I)*EL, 0}, {(-I)*EL, 0}, {I*EL, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-1/2*I)*EL^2)/sw, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{EL^2/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{((I/2)*EL)/sw, 0}, {((-1/2*I)*EL)/sw, 0}},

C[ S[3] , S[1] , -V[3] ] == {{EL/(2*sw), 0}, {-1/2*EL/sw, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{I*EL^2, 0}, {I*EL^2, 0}, {(-2*I)*EL^2, 0}},

C[ V[3] , -V[3] , V[2] ] == {{((-I)*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {((-I)*cw*EL)/sw, 0}, {(I*cw*EL)/sw, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{((-I)*EL^2)/sw^2, 0}, {((-I)*EL^2)/sw^2, 0}, {((2*I)*EL^2)/sw^2, 0}},

C[ F[1] , F[4] , S[3] ] == {{0, 0}, {-ye, 0}},

C[ F[2] , F[5] , S[3] ] == {{0, 0}, {-ym, 0}},

C[ F[3] , F[6] , S[3] ] == {{0, 0}, {-ytau, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[1] , V[2] ] == {{(EL*(cw^2 + sw^2))/(2*cw*sw), 0}, {-1/2*(EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ S[3] , -S[3] , V[2] ] == {{((I/2)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{EL^2/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-1/2*EL^2/cw, 0}},

C[ S[3] , -V[3] , V[2] ] == {{-1/2*(EL^2*vev)/cw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{((-2*I)*cw*EL^2)/sw, 0}, {(I*cw*EL^2)/sw, 0}, {(I*cw*EL^2)/sw, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(I*cw^2*EL^2)/sw^2, 0}, {(I*cw^2*EL^2)/sw^2, 0}, {((-2*I)*cw^2*EL^2)/sw^2, 0}},

C[ -F[4] , F[4] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[5] , F[5] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[6] , F[6] , V[1] ] == {{(-I)*EL, 0}, {(-I)*EL, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[1] ] == {{((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}, {((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[1] ] == {{((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}, {((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[1] ] == {{((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}, {((2*I)/3)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[1] ] == {{(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}, {(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[1] ] == {{(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}, {(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[1] ] == {{(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}, {(-1/3*I)*EL*IndexDelta[e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[4, {e3x2}] ] == {{I*GS*SUNT[e3x2, e1x2, e2x2], 0}, {I*GS*SUNT[e3x2, e1x2, e2x2], 0}},

C[ -F[8, {e1x2}] , F[11, {e2x2}] , V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[9, {e1x2}] , F[12, {e2x2}] , V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[7, {e1x2}] , F[10, {e2x2}] , V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[12, {e1x2}] , F[9, {e2x2}] , -V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[10, {e1x2}] , F[7, {e2x2}] , -V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[11, {e1x2}] , F[8, {e2x2}] , -V[3] ] == {{(I*EL*IndexDelta[e1x2, e2x2])/(Sqrt[2]*sw), 0}, {0, 0}},

C[ F[1] , F[4] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ F[2] , F[5] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ F[3] , F[6] , V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[4] , F[1] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[5] , F[2] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[6] , F[3] , -V[3] ] == {{(I*EL)/(Sqrt[2]*sw), 0}, {0, 0}},

C[ -F[8, {e1x2}] , F[8, {e2x2}] , V[2] ] == {{((I/6)*EL*(3*cw^2 - sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {(((-2*I)/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ -F[9, {e1x2}] , F[9, {e2x2}] , V[2] ] == {{((I/6)*EL*(3*cw^2 - sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {(((-2*I)/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ -F[7, {e1x2}] , F[7, {e2x2}] , V[2] ] == {{((I/6)*EL*(3*cw^2 - sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {(((-2*I)/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ -F[12, {e1x2}] , F[12, {e2x2}] , V[2] ] == {{((-1/6*I)*EL*(3*cw^2 + sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {((I/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ -F[10, {e1x2}] , F[10, {e2x2}] , V[2] ] == {{((-1/6*I)*EL*(3*cw^2 + sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {((I/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ -F[11, {e1x2}] , F[11, {e2x2}] , V[2] ] == {{((-1/6*I)*EL*(3*cw^2 + sw^2)*IndexDelta[e1x2, e2x2])/(cw*sw), 0}, {((I/3)*EL*sw*IndexDelta[e1x2, e2x2])/cw, 0}},

C[ F[1] , F[1] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {((-1/2*I)*EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ F[2] , F[2] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {((-1/2*I)*EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ F[3] , F[3] , V[2] ] == {{((I/2)*EL*(cw^2 + sw^2))/(cw*sw), 0}, {((-1/2*I)*EL*(cw^2 + sw^2))/(cw*sw), 0}},

C[ -F[4] , F[4] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}},

C[ -F[5] , F[5] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}},

C[ -F[6] , F[6] , V[2] ] == {{((-1/2*I)*EL*(cw - sw)*(cw + sw))/(cw*sw), 0}, {(I*EL*sw)/cw, 0}}

}

